### ISSUE TITLE
Nice-to-have: Enable teachers to hide certain groups or groupings

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-block_groups#12]
Teachers might want to use groups (or even groupings) for internal purposes only. In that case it is not desirable to communicate all groups to students.

Consequently, enable teachers hide groups, e.g. by creating settings that display a checkbox list of groupings. Disabling a grouping in the settings would indicate that all groups of that grouping should be hidden for students.

**Comment by tobiasreischmann** [comment]
Activities have a little 'eye' icon behind it, to hide or show it. This method could be replicated for the groups block. The teacher already gets a list of all existing groups and groupings in his course. Through, little icons behind each entry, the teacher could then allow the group to be displayed to the students in the block, or not. In this way, no additional settings page would be necessary.

**Comment by NinaHerrmann** [comment]
Eye icons enables teacher to hide/show groups. When the block is added to a course all groups are automatically hidden.
