### ISSUE TITLE
Upgrade Script for creation of block_groups_hide table

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-block_groups#14]
The database block_groups_hide is currently not created by the upgrade script. However, some moodle installations might have an old version block installed.

Test instructions:
- git checkout 188e3d6826df3586a9d04140578b53ff6d28fc4d
- Drop database and reinstall moodle
- Add at least one instance of block_groups
- git checkout master
- Update moodle and view block_groups

**Comment by NinaHerrmann** [comment]
For versions older than 2016042800 the file is not up to date.

**Comment by NinaHerrmann** [comment]
Since no one complained, and the bug is old the issue is closed.
