### ISSUE TITLE
No need for block/groups:myaddinstance

### ISSUE THREAD

**Issue by mudrd8mz** [learnweb/moodle-block_groups#15]
In its `applicable_formats()`, the block correctly declares not to be used on personal dashboards. IIRC, there is no need to declare the capability `block/groups:myaddinstance` then. It makes it only confusing.

**Comment by mudrd8mz** [comment]
Speaking of which, there is this mistake in the strings file:

```
$string['groups:myaddinstance'] = 'Add a new Group block';
$string['groups:myaddinstance'] = 'Add a new group block to Dashboard';
```

See the string defined twice. If the capability is to be removed, please do not forget to remove these strings, too.

**Comment by NinaHerrmann** [comment]
We thought this too, however travis does demand for myaddinstance. Therefore the capability is still in the code.
Thank you for your attentive reading the String will be fixed soon.

**Comment by mudrd8mz** [comment]
> however travis does demand for myaddinstance

Does it? It is their bug then and should be reported.

**Comment by NinaHerrmann** [comment]
Travis was updated, my addinstance removed.
