### ISSUE TITLE
SQL query inside foreach loop body

### ISSUE THREAD

**Issue by mudrd8mz** [learnweb/moodle-block_groups#17]
The method `build_grouping_array()` has the SQL query inside a foreach loop. It is generally considered as a very bad practise due to performance degradation on bigger scales. It is recommended to have constant amount of SQL queries.

In this example, there should be a single query that returns number of users per grouping for all groupings at once.

**Comment by NinaHerrmann** [comment]
Is now replaced by one sql-query which returns an array of all groupings.
