### ISSUE TITLE
Test for Moodle 3.1 support

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-block_groups#18]
There are some changes to the moodle API in moodle 3.1.
Have a look here: https://docs.moodle.org/dev/Moodle_3.1_release_notes#For_developers
Interesting could be:
MDL-51700 - Ajax service should clean the return values of the external functions
MDL-46891 - Upgrade to behat 3.x

**Comment by NinaHerrmann** [comment]
Test work now for moodle 3.1
