### ISSUE TITLE
Error Message every time setting a course to visible / invisible

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-block_groups#20]
Hi,

I'm testing your plugin right now. However, every time, when I want to set a group to visible / invisble I get the error message "The required change was not possible".
When I reload the page the change was appllied though.

I'm operating on Moodle 3.1 and we're using Postgres.

Cheers,
Kathrin

**Comment by NinaHerrmann** [comment]
Hello Kathrin,
Thanks for your feedback!
The new version (release v3.1-r3) should solve the given problem. The issue emerged since Moodle 3.1 checks the return parameter of Webservices. 
With kind regards 
Nina

**Comment by Kathrin84** [comment]
Hi Nina,
thanks a lot for the quick fix. It works. +1
I've got a little question about the version number of the new release: It has the same number as the release with the version v3.1-r1 from august. Is this a mistake or intended that way?
Cheers, Kathrin

**Comment by NinaHerrmann** [comment]
Hey Katrin,
Thanks for reviewing the new version!
I forgot about the version number so I decided to release another version. 
I hope the rest works fine.
Cheers, Nina
