### ISSUE TITLE
Adding possibility to set all groups visible or invisible with one click

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-block_groups#21]
Hi there,

at the moment (Release v3.1-r1) all the groups are hidden in the Block when adding it to a course. The  only way I found to set each group visible is by manually selecting each group and then clicking on the eye icon.

This is okay if I've got only a few groups in my course. However, in our university there are a lot of courses that have several hundred students enrolled and therefore also a whole bunch of groups. For this use case it's not such a good solution to manually activate each group.

I would suggest to make the groups visible as default by addding the block.
And then a function that enables to hide / show all groups with one click would be a nice feature.

[Edit:]
Further ideas:
* It would be nice if the admin and / or teacher could set the default behaviour if groups should be hidden or shown initally.
* Make it possible to hide / show groupings and with it also show / hide all existent and future new groups that belong to that grouping.

Cheers,
Kathrin

**Comment by NinaHerrmann** [comment]
Hey Kathrin,
Thanks for your Feedback! I am sorry the answer took so long. 
Anyway, the new version v3.3-r2 adds the possibility to change all groups with one click. For your other ideas, I will open additional issues, however I am currently missing time implement the functionalities. I think changing the visibility of groups by changing the visibility of groupings is an excellent idea and the next feature I will implement. 
Cheers,
Nina
