### ISSUE TITLE
Add a simple README.md file

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-block_groups#6]
containing
- TravisCI badge
- name, authors, and purpose of the block
- (missing) link to Moodle plugin directory
- Screenshots comparing teachers' and students'  views
- Installation instructions

**Comment by NinaHerrmann** [comment]
Still open since directory link is not available yet.

**Comment by mudrd8mz** [comment]
The link will be https://moodle.org/plugins/block_groups

**Comment by NinaHerrmann** [comment]
Thank you for your support, since the plugin is not confirmed by moodle, the link will be added as soon as it is possible.
