### ISSUE TITLE
$this->page->course->id or $COURSE->id?

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-block_groups#7]
Which one is better / encouraged by Moodle?

https://github.com/learnweb/moodle-block_groups/blob/master/block_groups.php#L135 vs. https://github.com/learnweb/moodle-block_groups/blob/master/block_groups.php#L92

I am not sure which one should be used, but I'd suggest not to use both.

**Comment by NinaHerrmann** [comment]
I decided for COURSE->id, I couldn't find any information about the preferences Moodle has.
